import {exportPrompts,importPrompts,transferLimit} from './prompt-transfer.mjs';
import {previewRu} from './translation-ru.mjs';
import {readPrompts,writePrompts,snapshotPrompt} from './saved-prompts.mjs';
import {compose,merge} from './composer.mjs';
const $=id=>document.getElementById(id), el=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
let selection=[],saved=[],openedPrompt=null,previewLanguage='en';const key='archviz-prompt-studio-v1';
// Decorative icons only; the native selects remain the controls.
const categoryIcons={'Geometry':'geometry','Materials':'material','Lighting':'light','Atmosphere':'atmosphere','Landscape':'landscape','Camera':'camera','People':'people','Quality':'qc','Negative / Restrictions':'restrictions','AI terminology':'mask','Object / 3D Asset':'geometry','Video':'camera'};
const presetIcons={'facade':'geometry','facade-travertine':'geometry','road':'road','greenery':'landscape','people':'people','interior':'interior','exterior':'geometry','final-polish':'polish','material-study':'material','day-→-night':'light','portfolio-polish':'polish','object-3d-asset':'geometry','archviz-video':'camera','object-video':'camera','first-last-video':'camera','environment-context':'landscape','night-lighting':'light','people-insertion':'people','season-spring':'landscape','season-summer':'landscape','season-autumn':'landscape','season-winter':'landscape','material-id-map':'mask','hdri-realism':'light'};
function icon(name){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg'),use=document.createElementNS('http://www.w3.org/2000/svg','use');svg.classList.add('ui-icon');svg.setAttribute('aria-hidden','true');use.setAttribute('href','#icon-'+name);svg.append(use);return svg;}
function decorateHeading(card,name){card.querySelector('h3').prepend(icon(name));}
function renderFieldIcons(){$('categoryIcon').replaceChildren(icon(categoryIcons[$('category').value]||'preset'));$('presetIcon').replaceChildren(icon(presetIcons[$('preset').value]||'preset'));}
function message(t){$('message').textContent=t;}
try {
const [library,dictionary,presets]=await Promise.all(['prompt_blocks','dictionary','presets'].map(async name=>{const r=await fetch(`data/${name}.json`);if(!r.ok)throw Error(`${name}: HTTP ${r.status}`);return r.json();}));
const byId=new Map(library.blocks.map(b=>[b.id,b]));
function valid(items){if(!Array.isArray(items)||items.length>200)throw Error('Неверный список блоков');return items.map(s=>{if(!s||!byId.has(s.id))throw Error('Неизвестный блок');const b=byId.get(s.id),parameters={};for(const [k,v] of Object.entries(s.parameters||{})){if(!(k in b.parameters)||typeof v!=='string'||v.length>2000)throw Error('Неверный параметр');parameters[k]=v;}return {id:s.id,parameters};});}
try{const data=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(data))throw Error();saved=data.map(p=>({name:String(p.name).slice(0,100),blocks:valid(p.blocks)}));}catch{message('Сохранения недоступны или повреждены. Можно использовать экспорт JSON.');}
function savedList(){ $('saved').replaceChildren(...saved.map((p,i)=>new Option(p.name,String(i))));}
function output(){const live=compose(library,selection),result=openedPrompt?{...live,text:openedPrompt.text}:live;$('openedPromptNote').hidden=!openedPrompt;const ru=previewLanguage==='ru'?previewRu(result.text,library):null;$('output').value=ru?ru.text:result.text;$('output').setAttribute('aria-label',ru?'Русский предварительный просмотр':'Итоговый prompt на английском');$('viewEn').setAttribute('aria-pressed',String(!ru));$('viewRu').setAttribute('aria-pressed',String(!!ru));$('translationNote').hidden=!ru;$('translationNote').textContent=ru?.incomplete?'Перевод для понимания. Непереведённые фрагменты и пользовательские значения отмечены [EN: …]. Copy EN и Save Prompt используют английский оригинал.':'Перевод для понимания. Copy EN и Save Prompt используют английский оригинал.';$('warnings').replaceChildren();if(result.warnings.length){const w=el('div','Конфликт блоков: '+result.warnings.join('; ')+'. Удалите несовместимый блок перед копированием.');w.className='warning';$('warnings').append(w);}return result;}
function renderSelected(){ $('selected').replaceChildren();for(const [i,item] of selection.entries()){const b=byId.get(item.id),card=el('div');card.className='card';card.append(el('h3',b.en),el('p',b.ru));decorateHeading(card,categoryIcons[b.category]||'reference');for(const [k,v] of Object.entries(b.parameters)){const label=el('label',({scale:'Масштаб фактуры',joints:'Швы',roughness:'Шероховатость',weathering:'Старение'})[k]||k),input=el('input');input.value=item.parameters[k]??v;input.maxLength=2000;input.oninput=()=>{openedPrompt=null;item.parameters[k]=input.value;output();};label.append(input);card.append(label);}const remove=el('button','Удалить');remove.className='quiet';remove.onclick=()=>{openedPrompt=null;selection.splice(i,1);renderSelected();};card.append(remove);$('selected').append(card);}output();}
function add(ids){openedPrompt=null;selection=merge(selection,ids);renderSelected();}
function renderLibrary(){const q=$('search').value.toLowerCase(),category=$('category').value;const matches=dictionary.filter(d=>(!category||d.category===category)&&JSON.stringify(d).toLowerCase().includes(q));$('count').textContent=matches.length+' блоков';$('library').replaceChildren();for(const d of matches){const b=byId.get(d.block_id),card=el('article');card.className='card';card.append(el('small',d.category+' / '+b.status),el('h3',d.term_en),el('p',d.term_ru),el('p',d.description_ru));const details=el('details');details.append(el('summary','Технический блок EN'),el('p',b.text));card.append(details);decorateHeading(card,categoryIcons[d.category]||'reference');const btn=el('button','+ Add to Prompt');btn.onclick=()=>add([b.id]);card.append(btn);$('library').append(card);}}
for(const c of [...new Set(dictionary.map(d=>d.category))].sort())$('category').append(new Option(c,c));
for(const p of presets)$('preset').append(new Option(p.name,p.id));
$('viewEn').onclick=()=>{previewLanguage='en';output();};$('viewRu').onclick=()=>{previewLanguage='ru';output();};
$('search').oninput=renderLibrary;$('category').onchange=()=>{renderFieldIcons();renderLibrary();};$('preset').onchange=renderFieldIcons;
$('addPreset').onclick=()=>add(presets.find(p=>p.id===$('preset').value).blocks);
$('clear').onclick=()=>{openedPrompt=null;selection=[];renderSelected();};
$('copy').onclick=async()=>{const r=output();if(!r.text)return message('Сначала добавьте блоки.');if(r.warnings.length)return message('Копирование остановлено: разрешите конфликты блоков.');try{await navigator.clipboard.writeText(r.text);message('Prompt скопирован.');}catch{previewLanguage='en';output();$('output').focus();$('output').select();message('Нажмите Ctrl+C для копирования.');}};
$('save').onclick=()=>{const name=$('name').value.trim();if(!name||!selection.length)return message('Введите название и добавьте блоки.');if(saved.some(p=>p.name===name))return message('Такое имя уже есть. Используйте новое имя.');const next=[...saved,{name,blocks:structuredClone(selection)}];try{localStorage.setItem(key,JSON.stringify(next));saved=next;savedList();message('Комбинация сохранена в браузере.');}catch{message('Не удалось сохранить. Используйте экспорт JSON.');}};
$('load').onclick=()=>{const p=saved[Number($('saved').value)];if(!p)return;openedPrompt=null;const ids=new Set(selection.map(s=>s.id));selection.push(...structuredClone(p.blocks.filter(s=>!ids.has(s.id))));renderSelected();};
$('export').onclick=()=>{const a=el('a'),url=URL.createObjectURL(new Blob([JSON.stringify({schema_version:1,name:$('name').value||'My Combination',blocks:selection},null,2)],{type:'application/json'}));a.href=url;a.download='archviz-combination.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>1000000)throw Error('Файл больше 1 МБ');const data=JSON.parse(await f.text());if(data.schema_version!==1)throw Error('Неподдерживаемая версия');const items=valid(data.blocks),ids=new Set(selection.map(s=>s.id));openedPrompt=null;selection.push(...items.filter(s=>!ids.has(s.id)&&ids.add(s.id)));renderSelected();message('Комбинация добавлена. Существующие параметры сохранены.');}catch(err){message('Импорт отменён: '+err.message);}finally{e.target.value='';}};
const promptStorage={getItem:key=>window.localStorage.getItem(key),setItem:(key,value)=>window.localStorage.setItem(key,value)};
const loadedPrompts=readPrompts(promptStorage,library,presets);let promptData=loadedPrompts.data;const promptStorageError=loadedPrompts.error;
function promptMessage(text){$('promptLibraryMessage').textContent=text;}
function persistPrompts(next){if(promptStorageError){promptMessage(promptStorageError);return false;}try{promptData=writePrompts(promptStorage,next,library,presets);return true;}catch{promptMessage('Не удалось сохранить Saved Prompts. Запись не изменена.');return false;}}
async function copySavedPrompt(p){try{await navigator.clipboard.writeText(p.text);promptMessage('Сохранённый EN prompt скопирован.');}catch{previewLanguage='en';openSavedPrompt(p);$('output').focus();$('output').select();promptMessage('Текст выделен. Нажмите Ctrl+C.');}}
function openSavedPrompt(p){selection=p.blockIds.map(id=>({id,parameters:{...p.parameters[id]}}));$('preset').value=p.scenario;renderFieldIcons();renderSelected();openedPrompt=p;$('promptName').value=p.name;output();$('output').focus();}
function downloadPrompts(data,filename){try{const text=exportPrompts(data,library,presets),a=el('a'),url=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);promptMessage('JSON готов к переносу.');}catch(err){promptMessage('Экспорт отменён: '+err.message);}}
$('exportPrompts').onclick=()=>{if(promptStorageError)return promptMessage(promptStorageError);if(!promptData.prompts.length)return promptMessage('Нет сохранённых промптов для экспорта.');downloadPrompts(promptData,'archviz-saved-prompts.json');};
$('importPrompts').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(promptStorageError)throw Error(promptStorageError);if(file.size>transferLimit)throw Error('Файл больше 10 МБ');const result=importPrompts(await file.text(),promptData,library,presets);if(!result.added){promptMessage('Добавлено: 0. Уже есть: '+result.skipped+'.');return;}if(persistPrompts(result.data)){renderPrompts();promptMessage('Добавлено: '+result.added+'. Уже есть: '+result.skipped+'.');}}catch(err){promptMessage('Импорт отменён: '+err.message);}finally{e.target.value='';}};
function renderPrompts(){$('savedPrompts').replaceChildren();for(const p of promptData.prompts){const card=el('article');card.className='card saved-prompt-card';card.append(el('h3',p.name),el('small',presets.find(s=>s.id===p.scenario).name),el('p',p.text.slice(0,180)+(p.text.length>180?'…':'')));const date=el('time',new Date(p.createdAt).toLocaleString('ru-RU'));date.dateTime=p.createdAt;card.append(date);const actions=el('div');actions.className='saved-prompt-actions';for(const [label,action] of [['Open / Load',()=>openSavedPrompt(p)],['Copy',()=>copySavedPrompt(p)],['Export',()=>downloadPrompts({schema_version:1,prompts:[p]},'archviz-saved-prompt.json')],['Delete',()=>{if(persistPrompts({...promptData,prompts:promptData.prompts.filter(x=>x.id!==p.id)})){renderPrompts();promptMessage('Saved Prompt удалён.');}}]]){const button=el('button',label);button.onclick=action;actions.append(button);}card.append(actions);$('savedPrompts').append(card);}if(!promptData.prompts.length)$('savedPrompts').append(el('p','Сохраните готовый Final Prompt, чтобы он появился здесь.'));}
$('savePrompt').onclick=()=>{const result=output(),name=$('promptName').value.trim();if(!name||!result.text)return message('Введите название готового промпта и добавьте блоки.');if(result.warnings.length)return message('Save Prompt остановлен: разрешите конфликты.');const p=snapshotPrompt({id:crypto.randomUUID(),name,scenario:openedPrompt?.scenario||$('preset').value,text:result.text,selection,library,createdAt:new Date().toISOString()});if(persistPrompts({...promptData,prompts:[...promptData.prompts,p]})){renderPrompts();promptMessage('Готовый prompt сохранён.');}};
renderPrompts();if(promptStorageError)promptMessage(promptStorageError);

renderFieldIcons();savedList();renderLibrary();renderSelected();
}catch(err){message('Ошибка загрузки: '+err.message+'. Откройте сайт через HTTP, а не file://.');}
