import {compose,merge} from './composer.mjs';
const $=id=>document.getElementById(id), el=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
let selection=[],saved=[];const key='archviz-prompt-studio-v1';
function message(t){$('message').textContent=t;}
try {
const [library,dictionary,presets]=await Promise.all(['prompt_blocks','dictionary','presets'].map(async name=>{const r=await fetch(`data/${name}.json`);if(!r.ok)throw Error(`${name}: HTTP ${r.status}`);return r.json();}));
const byId=new Map(library.blocks.map(b=>[b.id,b]));
function valid(items){if(!Array.isArray(items)||items.length>200)throw Error('Неверный список блоков');return items.map(s=>{if(!s||!byId.has(s.id))throw Error('Неизвестный блок');const b=byId.get(s.id),parameters={};for(const [k,v] of Object.entries(s.parameters||{})){if(!(k in b.parameters)||typeof v!=='string'||v.length>2000)throw Error('Неверный параметр');parameters[k]=v;}return {id:s.id,parameters};});}
try{const data=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(data))throw Error();saved=data.map(p=>({name:String(p.name).slice(0,100),blocks:valid(p.blocks)}));}catch{message('Сохранения недоступны или повреждены. Можно использовать экспорт JSON.');}
function savedList(){ $('saved').replaceChildren(...saved.map((p,i)=>new Option(p.name,String(i))));}
function output(){const result=compose(library,selection);$('output').value=result.text;$('warnings').replaceChildren();if(result.warnings.length){const w=el('div','Конфликт блоков: '+result.warnings.join('; ')+'. Удалите несовместимый блок перед копированием.');w.className='warning';$('warnings').append(w);}return result;}
function renderSelected(){ $('selected').replaceChildren();for(const [i,item] of selection.entries()){const b=byId.get(item.id),card=el('div');card.className='card';card.append(el('h3',b.en),el('p',b.ru));for(const [k,v] of Object.entries(b.parameters)){const label=el('label',({scale:'Масштаб фактуры',joints:'Швы',roughness:'Шероховатость',weathering:'Старение'})[k]||k),input=el('input');input.value=item.parameters[k]??v;input.maxLength=2000;input.oninput=()=>{item.parameters[k]=input.value;output();};label.append(input);card.append(label);}const remove=el('button','Удалить');remove.className='quiet';remove.onclick=()=>{selection.splice(i,1);renderSelected();};card.append(remove);$('selected').append(card);}output();}
function add(ids){selection=merge(selection,ids);renderSelected();}
function renderLibrary(){const q=$('search').value.toLowerCase(),category=$('category').value;const matches=dictionary.filter(d=>(!category||d.category===category)&&JSON.stringify(d).toLowerCase().includes(q));$('count').textContent=matches.length+' блоков';$('library').replaceChildren();for(const d of matches){const b=byId.get(d.block_id),card=el('article');card.className='card';card.append(el('small',d.category+' / '+b.status),el('h3',d.term_en),el('p',d.term_ru),el('p',d.description_ru));const details=el('details');details.append(el('summary','Технический блок EN'),el('p',b.text));card.append(details);const btn=el('button','+ Add to Prompt');btn.onclick=()=>add([b.id]);card.append(btn);$('library').append(card);}}
for(const c of [...new Set(dictionary.map(d=>d.category))].sort())$('category').append(new Option(c,c));
for(const p of presets)$('preset').append(new Option(p.name,p.id));
$('search').oninput=renderLibrary;$('category').onchange=renderLibrary;
$('addPreset').onclick=()=>add(presets.find(p=>p.id===$('preset').value).blocks);
$('clear').onclick=()=>{selection=[];renderSelected();};
$('copy').onclick=async()=>{const r=output();if(!r.text)return message('Сначала добавьте блоки.');if(r.warnings.length)return message('Копирование остановлено: разрешите конфликты блоков.');try{await navigator.clipboard.writeText(r.text);message('Prompt скопирован.');}catch{$('output').focus();$('output').select();message('Нажмите Ctrl+C для копирования.');}};
$('save').onclick=()=>{const name=$('name').value.trim();if(!name||!selection.length)return message('Введите название и добавьте блоки.');if(saved.some(p=>p.name===name))return message('Такое имя уже есть. Используйте новое имя.');const next=[...saved,{name,blocks:structuredClone(selection)}];try{localStorage.setItem(key,JSON.stringify(next));saved=next;savedList();message('Комбинация сохранена в браузере.');}catch{message('Не удалось сохранить. Используйте экспорт JSON.');}};
$('load').onclick=()=>{const p=saved[Number($('saved').value)];if(!p)return;const ids=new Set(selection.map(s=>s.id));selection.push(...structuredClone(p.blocks.filter(s=>!ids.has(s.id))));renderSelected();};
$('export').onclick=()=>{const a=el('a'),url=URL.createObjectURL(new Blob([JSON.stringify({schema_version:1,name:$('name').value||'My Combination',blocks:selection},null,2)],{type:'application/json'}));a.href=url;a.download='archviz-combination.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>1000000)throw Error('Файл больше 1 МБ');const data=JSON.parse(await f.text());if(data.schema_version!==1)throw Error('Неподдерживаемая версия');const items=valid(data.blocks),ids=new Set(selection.map(s=>s.id));selection.push(...items.filter(s=>!ids.has(s.id)&&ids.add(s.id)));renderSelected();message('Комбинация добавлена. Существующие параметры сохранены.');}catch(err){message('Импорт отменён: '+err.message);}finally{e.target.value='';}};
savedList();renderLibrary();renderSelected();
}catch(err){message('Ошибка загрузки: '+err.message+'. Откройте сайт через HTTP, а не file://.');}
